name: Make PDF on Merge

on:
  push:
    branches: [main]
    tags-ignore: ["v*"]

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container:
      image: pandoc/extra:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compute new version
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          tag_prefix: v

      - name: Install Noto Fonts
        run: |
          apk add --no-cache fontconfig font-noto 
          fc-cache -fv
          mktexlsr || true

      - name: Setup Buildinfo
        run: |
          DATE="$(date -u '+%m-%d-%Y')"
          echo "\renewcommand{\version}{\texttt{\detokenize{${{ steps.tag.outputs.new_tag }}}}}" >> build/buildinfo.tex
          echo "\renewcommand{\builddate}{$DATE}" >> build/buildinfo.tex

      - name: Build PDF with Pandoc
        run: |
          TEXINPUTS=".:tex//:" pandoc ccdc-bible.md \
          --metadata-file=build/meta.yaml \
          --include-in-header=build/preamble.tex \
          --include-in-header=build/buildinfo.tex \
          --toc \
          -o ccdc-bible-${{ steps.tag.outputs.new_tag }}.pdf \
          --pdf-engine=xelatex \
          --listings \
          --lua-filter=build/h2-pagebreak.lua \
          --lua-filter=build/tipbox.lua \

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: "Release ${{ steps.tag.outputs.new_tag }}"
          body: "Automated build"
          draft: false
          prerelease: flase
          make_latest: true
          files: |
            ccdc-bible-${{ steps.tag.outputs.new_tag }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

